# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    CA:
        Country: US
        Province: California
        Locality: San Francisco
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
      - Hostname: orderer6
      - Hostname: orderer7
      - Hostname: orderer8
      - Hostname: orderer9
      - Hostname: orderer10
      - Hostname: orderer11
      - Hostname: orderer12
      - Hostname: orderer13
      - Hostname: orderer14
      - Hostname: orderer15
      - Hostname: orderer16
      - Hostname: orderer17
      - Hostname: orderer18
      - Hostname: orderer19
      - Hostname: orderer20
      - Hostname: orderer21
      - Hostname: orderer22
      - Hostname: orderer23
      - Hostname: orderer24
      - Hostname: orderer25
      - Hostname: orderer26
      - Hostname: orderer27
      - Hostname: orderer28
      - Hostname: orderer29
      - Hostname: orderer30
      - Hostname: orderer31
      - Hostname: orderer32
      - Hostname: orderer33
      - Hostname: orderer34
      - Hostname: orderer35
      - Hostname: orderer36
      - Hostname: orderer37
      - Hostname: orderer38
      - Hostname: orderer39
      - Hostname: orderer40
      - Hostname: orderer41
      - Hostname: orderer42
      - Hostname: orderer43
      - Hostname: orderer44
      - Hostname: orderer45
      - Hostname: orderer46
      - Hostname: orderer47
      - Hostname: orderer48
      - Hostname: orderer49
      - Hostname: orderer50
      - Hostname: orderer51
      - Hostname: orderer52
      - Hostname: orderer53
      - Hostname: orderer54
      - Hostname: orderer55
      - Hostname: orderer56
      - Hostname: orderer57
      - Hostname: orderer58
      - Hostname: orderer59
      - Hostname: orderer60
      - Hostname: orderer61
      - Hostname: orderer62
      - Hostname: orderer63
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    CA:
        Country: US
        Province: California
        Locality: San Francisco
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    #   - Hostname:   (Required) The desired hostname, sans the domain.
    #   - CommonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: foo # implicitly "foo.org1.example.com"
    #     CommonName: foo27.org5.example.com # overrides Hostname-based FQDN set above
    #   - Hostname: bar
    #   - Hostname: baz
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # ---------------------------------------------------------------------------
    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    CA:
        Country: US
        Province: California
        Locality: San Francisco
    Template:
      Count: 2
    Users:
      Count: 1
